### ISSUE TITLE
关于react-navigation中滑动返回的问题

### ISSUE THREAD

**Issue by dautent** [hanxiaofeng/ReactNAndroidOne#1]
```
    //自定义界面跳转左右切换动画
    transitionConfig:()=>({
        screenInterpolator: CardStackStyleInterpolator.forHorizontal,
    }),
```
看到你博客中引用了上面的代码设置滑动返回（Android），但是我想设置滑动的阈值通过` gestureResponseDistance: {horizontal: 300},`这样的方法好像不起作用，请问你这边可以改变阈值吗？
ps：不知道为什么你的代码在我这没有跑起来

**Comment by hanxiaofeng** [comment]
@dautent 不好意思，刚看到，好久没弄rn了，百度google下吧（手动滑稽）
